### PR TITLE
JOSS reviews

### PR DESCRIPTION
**Pull request by auggiemarignier**
Implement changes suggested by reviewers of JOSS paper

### CODE REVIEW

**Comment by auggiemarignier** [comment]
It was recommended to add descriptive comments to the example scripts

**Comment by mattpitkin** [comment]
Great, thanks very much for adding in the additional detail, code comments and usage descriptions. It looks good to me.

**Comment by auggiemarignier** [comment]
Keeping version string in `__init__.py` consistent with package version in `pyproject.toml` #17

**Comment by auggiemarignier** [comment]
Make the topography example run quickly, just as a quickstart

**Comment by mattpitkin** [comment]
In your `pyproject.toml` file, can you add an `extras` that installs all the requirements for running the examples in the `experiments` folder? For example, the `earthtopography` example, requires `healpy`, so you might at least want:

```python
[tool.poetry.extras]
...
experiments = ["healpy"]
```

Then in the README for earthtopography add something like: "This example requires the healpy package. If you have build pxmcmc from source you can make sure this is installed by rebuilding with `poetry install -E experiments`, or manually install healpy with your preferred package manager, e.g., `pip install healpy`."

**Comment by auggiemarignier** [comment]
@mattpitkin I agree this would be a good idea. It would reduce the installation time quite significantly if I can move some of these dependencies out to just the examples.  The thing is I think it's only `healpy` that's not really used in the `pxmcmc` API.  Things like `pyssht` and `pys2let` are used in the `pxmcmc.transforms`, `pxmcmc.priors` and `pxmcmc.plotting` modules because when I first wrote the code it was intended for spherical problems, but ultimately with the class-based API it can be used for anything.

What I could do is move all the spherical stuff into the `experiments` directory, leaving `pxmcmc` to only contain abstract classes and the actual PxMCMC implementations.

That's annoying about `pys2let`, I thought all the installation issues were sorted with v2.2.5.  But didn't you say before you were able to install the whole package using `poetry`? which just uses `pip`

**Comment by mattpitkin** [comment]
I think my main problem (which kind of voids my last comment to an extent) was that I hadn't actually installed pxmcmc before attempting to run the experiment example! Sorry about that! It might still be worth moving some dependencies that are only required for the examples into optional "extras", but it's not something that I'll make a major push for given that they are already requirements of the full package.

> That's annoying about pys2let, I thought all the installation issues were sorted with v2.2.5. But didn't you say before you were able to install the whole package using poetry? which just uses pip

That said, I pys2let is still causing me issues. I _had_ been able to install pxmcmc, including pys2let, it on my Windows machine running Ubuntu (via WSL2), however when I try installing on my actual Linux machine (Ubuntu 20.04.06, Python 3.9.16, pip 23.2, poetry 1.5.1) I get the error:

```
  CMake Error at /tmp/tmpteo7l8pi/.venv/lib/python3.9/site-packages/skbuild/resources/cmake/FindPythonExtensions.cmake:245 (find_package):
    By not providing "FindPythonInterp.cmake" in CMAKE_MODULE_PATH this project
    has asked CMake to find a package configuration file provided by
    "PythonInterp", but CMake did not find one.
  
    Could not find a package configuration file provided by "PythonInterp" with
    any of the following names:
  
      PythonInterpConfig.cmake
      pythoninterp-config.cmake
  
    Add the installation prefix of "PythonInterp" to CMAKE_PREFIX_PATH or set
    "PythonInterp_DIR" to a directory containing one of the above files.  If
    "PythonInterp" provides a separate development package or SDK, be sure it
    has been installed.
  Call Stack (most recent call first):
    CMakeLists.txt:49 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  Traceback (most recent call last):
    File "/tmp/tmpteo7l8pi/.venv/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 666, in setup
      env = cmkr.configure(
    File "/tmp/tmpteo7l8pi/.venv/lib/python3.9/site-packages/skbuild/cmaker.py", line 357, in configure
      raise SKBuildError(msg)
  
  An error occurred while configuring with CMake.
    Command:
      /tmp/tmpteo7l8pi/.venv/lib/python3.9/site-packages/cmake/data/bin/cmake /tmp/tmpbr4t6xo_/pys2let-2.2.5 -G Ninja -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/tmpteo7l8pi/.venv/lib/python3.9/site-packages/ninja/data/bin/ninja --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX:PATH=/tmp/tmpbr4t6xo_/pys2let-2.2.5/_skbuild/linux-x86_64-3.9/cmake-install -DPYTHON_VERSION_STRING:STRING=3.9.16 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/tmpteo7l8pi/.venv/lib/python3.9/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/tmp/tmpteo7l8pi/.venv/bin/python -DPYTHON_INCLUDE_DIR:PATH=/home/matt/miniconda3/envs/pxmcmc/include/python3.9 -DPYTHON_LIBRARY:PATH=/home/matt/miniconda3/envs/pxmcmc/lib/libpython3.9.so -DPython_EXECUTABLE:PATH=/tmp/tmpteo7l8pi/.venv/bin/python -DPython_ROOT_DIR:PATH=/tmp/tmpteo7l8pi/.venv -DPython_FIND_REGISTRY:STRING=NEVER -DPython_INCLUDE_DIR:PATH=/home/matt/miniconda3/envs/pxmcmc/include/python3.9 -DPython_NumPy_INCLUDE_DIRS:PATH=/tmp/tmpteo7l8pi/.venv/lib/python3.9/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/tmp/tmpteo7l8pi/.venv/bin/python -DPython3_ROOT_DIR:PATH=/tmp/tmpteo7l8pi/.venv -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_INCLUDE_DIR:PATH=/home/matt/miniconda3/envs/pxmcmc/include/python3.9 -DPython3_NumPy_INCLUDE_DIRS:PATH=/tmp/tmpteo7l8pi/.venv/lib/python3.9/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/tmpteo7l8pi/.venv/lib/python3.9/site-packages/ninja/data/bin/ninja -DBUILD_TESTING:BOOL=OFF -Dconan_deps:BOOL=ON -Dcfitsio:BOOL=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      /tmp/tmpbr4t6xo_/pys2let-2.2.5
    Working directory:
      /tmp/tmpbr4t6xo_/pys2let-2.2.5/_skbuild/linux-x86_64-3.9/cmake-build
  Please see CMake's output for more information.
```

**Comment by mattpitkin** [comment]
Bizarrely, pys2let (v2.2.5) now no longer installs on my Windows machine in WSL2 either. When I try installing it in the same conda environment in which it had previously built (I removed it as a test), and it no longer builds. This is odd!

**Comment by jeremiecoullon** [comment]
> topography example

This is great! I really like the animation you add which shows how it converges to the correct solution.

Small nitpicks about this:
- [ ] The main readme (in root) needs updating (it says that you don't provide data for the example). Maybe link to the topography example readme, and you could even include the code to run that example in the main readme as well. As I mentioned before, the idea is to remove as much friction as possible for someone to run your code and get some plots out quickly just to check that everything works.

**Comment by jeremiecoullon** [comment]
Another small thing: could you add a 1-liner in the "About" section in the root page of your repo (top-right corner). You could also include the link to the documentation there which would be useful. I find that adding this makes a repo feel more "official" and more likely to be maintained :)

**Comment by mattpitkin** [comment]
> Bizarrely, pys2let (v2.2.5) now no longer installs on my Windows machine in WSL2 either. When I try installing it in the same conda environment in which it had previously built (I removed it as a test), and it no longer builds. This is odd!

I've been able to successfully get things to build again by using the conda-forge versions of `cmake` and `conan`, i.e., doing:

```bash
$ conda install -c conda-forge cmake conan"=1"
```

This then allows `pys2let` to build with:

```bash
$ pip install pys2let`
```

and `pxmcmc` will install properly too.

This evening, I'll try running the examples again and after that I think I'll be ready to sign-off the review.

**Comment by mattpitkin** [comment]
> This evening, I'll try running the examples again and after that I think I'll be ready to sign-off the review.

I've actually run this now - including upping the number of samples for the earth topography example and producing a nice looking result.

**Comment by auggiemarignier** [comment]
thanks @jeremiecoullon!

**Comment by auggiemarignier** [comment]
thanks @mattpitkin! `pys2let` has always been a pain to install, and it's much better than it was.  I think your problem was just the `conda` environment sticking with `conan2`, and `pys2let` needs to be fixed for `conan1`.  Glad it's sorted!

**Comment by auggiemarignier** [comment]
oh and would you look at that. The CI is now having that problem...

**Comment by auggiemarignier** [comment]
Merging and will resolve pys2let issues in due course #19

**Pull request merged**
